# creating a cron job to execute alpine pod once a day at midnight
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-cronjob
spec:
  schedule: "* * * * *" #10 0 * * 1-5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine-cronjob
            image: alpine
            command: ["/bin/sh"]
            args: ["-c", "sleep 5s; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure