# Daemonset to run alpine pod with name log-collector 
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector-ds
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
      - name: log-collector
        image: alpine
        args: ["sleep", "1d"]
      