---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
    - name: checkdb
      image: alpine
      args:
        - sleep
        - "11s"
    - name: checkapi
      image: alpine
      args:
        - sleep
        - "11s"
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: "TCP"
