---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo-app-config
data:
  HOST_NAME: "Test123"
  DB_USER: "dmt"
  DEBUG_LEVEL: "INFO"

# load config from configmap as environmental variables 
# in alpine pode
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-env-pod
spec:
  containers:
    - name: alpine-env-container
      image: alpine
      args: ["sleep", "1d"]
      envFrom:
        - configMapRef:
            name: cm-demo-app-config

# load config from configmap as volume
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-volume-pod
spec:
  containers:
    - name: alpine-volume-container
      image: alpine
      args: ["sleep", "1d"]
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: cm-demo-app-config