# basic secret manifest
---
apiVersion: v1
kind: Secret
metadata:
  name: dmt-secret
data:
  username: ZG10
  password: ZG10QDEyMw==
  database: bm9w
  host: bG9jYWxob3N0

# mount secret as volume to a pod
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: secret-volume-pod
      image: alpine
      args:
        - sleep
        - "1d"
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: dmt-secret