---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    type: database
spec:
  containers:
    - name: db
      image: mysql:8.0-debian
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: "rootroot"
       - name: MYSQL_DATABASE
         value: "employees"
       - name: MYSQL_USER
         value: "dmt"
       - name: MYSQL_PASSWORD
         value: "dmtdmt"
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbvol
  volumes:
    - persistentVolumeClaim:
        claimName: mysql-pvc
      name: dbvol