---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: db
      image: mysql:8.0-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_USER
          value: dmt
        - name: MYSQL_PASSWORD
          value: dmtdmt
        - name: MYSQL_DATABASE
          value: books
      ports:
        - containerPort: 3306
          protocol: "TCP"
          name: dbport
      volumeMounts:
        - name: booksdb
          mountPath: /var/lib/mysql
  volumes:
    - name: booksdb
      persistentVolumeClaim:
        claimName: mysql-pvc
      

