---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
  labels:
    component: web
    workload: rs
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: v1.0
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
              name: nginx_port
              protocol: "TCP"
      