---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: qa
  labels:
    app: web
    env: qa
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          name: webport
---
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    component: service
  namespace: qa
spec:
  type: ClusterIP
  selector:
    app: web
    env: qa
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 80
  
  


