---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-cm
data:
  DEBUG: INFO
  DB_HOST: mysql-svc
  DB_NAME: sample_db
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-1
spec:
  containers:
    - name: sample-container
      image: nginx:1.16
      envFrom:
        - configMapRef:
            name: sample-cm
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      configMap:
        name: sample-cm
        items:
          - key: DEBUG
            path: DEBUG
          - key: DB_HOST
            path: DB_HOST
          - key: DB_NAME
            path: DB_NAME