---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: test
      image: alpine
      command:
        - sleep
        - 1d