---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    env: dev
    app: web
spec:
  initContainers:
    - name: init-1
      image: alpine
      command:
        - sleep 
        - 5s
    - name: init-2
      image: alpine
      command:
        - sleep 
        - 6s
  containers:
    - name: nginx
      image: nginx