---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: web
          image: shaikkhajaibrahim/dmtest:1.0
          ports:
            - name: webport
              containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
    