---
apiVersion: v1
kind: Service
metadata:
  name: web-np
  labels:
    component: service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 80